### ISSUE TITLE
Crash while testing in small modpack, "onGetMouseOver(ClientProxy.java:345)"

### ISSUE THREAD

**Issue by dariusfontan** [JamiesWhiteShirt/clothesline#12]
Hi there, love your mod, it's really fun, thank you!
I just experienced a crash while messing around in a testing world with a couple of mods.
The crash came as I was in a boat rowing on snow, dunno if thats relevant :).
No items of your mod were placed in the world or in my inventory,
the crashlog points to your mod.
Here's the log, hope it helps:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.7.4 (1).jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  LoadingPlugin (Quark-r1.5-129.jar)
  clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.0.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 10/13/18 10:42 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.jamieswhiteshirt.clothesline.client.ClientProxy.onGetMouseOver(ClientProxy.java:345)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1014_ClientProxy_onGetMouseOver_GetMouseOverEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.jamieswhiteshirt.clothesline.hooks.ClientHooks.onGetMouseOver(ClientHooks.java:13)
	at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:591)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1589)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.jamieswhiteshirt.clothesline.client.ClientProxy.onGetMouseOver(ClientProxy.java:345)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1014_ClientProxy_onGetMouseOver_GetMouseOverEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.jamieswhiteshirt.clothesline.hooks.ClientHooks.onGetMouseOver(ClientHooks.java:13)
	at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:591)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1589)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['barttraeger'/2508, l='MpServer', x=278.02, y=68.55, z=300.06]]
	Chunk stats: MultiplayerChunkCache: 287, 287
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (185,64,302), Chunk: (at 9,4,14 in 11,18; contains blocks 176,0,288 to 191,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 45938 game time, 202679 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 53 total; [item.vehicleSpawner.20::18758 @ 260.25, 68.00, 408.73  -- y:123.75 p:0.00 -- m: 0.00, 0.00, 0.00, EntityShade['Shade'/162433, l='MpServer', x=321.76, y=58.00, z=309.00], EntityCrocodile['Crocodile'/6839, l='MpServer', x=301.91, y=80.00, z=241.93], EntityCrocodile['Crocodile'/6840, l='MpServer', x=292.50, y=78.00, z=243.00], EntitySkeleton['Skeleton'/162570, l='MpServer', x=266.50, y=37.00, z=229.50], EntityCreeper['Creeper'/162579, l='MpServer', x=309.50, y=25.00, z=300.50], EntityItem['item.tile.gravel'/162754, l='MpServer', x=340.25, y=26.00, z=260.94], EntityItem['item.tile.gravel'/162755, l='MpServer', x=343.33, y=26.00, z=260.00], EntityItem['item.tile.gravel'/162758, l='MpServer', x=333.32, y=24.00, z=259.62], EntityItem['item.tile.gravel'/162756, l='MpServer', x=338.74, y=29.00, z=257.34], EntityItem['item.tile.gravel'/162757, l='MpServer', x=340.72, y=27.00, z=259.25], EntityGhost['Ghost'/46026, l='MpServer', x=321.50, y=60.00, z=323.50], EntityItem['item.tile.gravel'/162778, l='MpServer', x=314.01, y=12.00, z=247.13], EntityZombie['Zombie'/162808, l='MpServer', x=266.80, y=14.00, z=270.49], EntitySkeleton['Skeleton'/162844, l='MpServer', x=269.21, y=39.00, z=226.47], EntityFly['Fly'/162884, l='MpServer', x=253.93, y=71.11, z=297.07], EntityItem['item.tile.gravel'/7401, l='MpServer', x=307.91, y=20.00, z=274.26], EntityCrocodile['Crocodile'/163158, l='MpServer', x=315.50, y=84.00, z=241.00], EntityItem['item.tile.gravel'/7553, l='MpServer', x=316.81, y=50.00, z=303.35], EntityCrocodile['Crocodile'/163218, l='MpServer', x=260.91, y=64.00, z=242.99], EntityCrocodile['Crocodile'/163219, l='MpServer', x=266.90, y=71.00, z=245.97], EntityCrocodile['Crocodile'/163226, l='MpServer', x=289.50, y=67.00, z=234.50], EntityCrocodile['Crocodile'/163228, l='MpServer', x=317.39, y=81.00, z=234.98], EntityCrocodile['Crocodile'/163267, l='MpServer', x=281.97, y=95.00, z=242.88], EntityCrocodile['Crocodile'/163271, l='MpServer', x=315.90, y=81.00, z=232.93], EntityCrocodile['Crocodile'/163269, l='MpServer', x=281.50, y=79.00, z=242.50], EntityBoat['Boat'/163287, l='MpServer', x=278.02, y=69.00, z=300.06], EntityCrocodile['Crocodile'/163303, l='MpServer', x=292.83, y=75.00, z=239.50], EntityCrocodile['Crocodile'/163301, l='MpServer', x=306.00, y=64.00, z=232.02], EntityCrocodile['Crocodile'/163315, l='MpServer', x=263.92, y=74.00, z=245.88], EntityZombie['Zombie'/163312, l='MpServer', x=268.50, y=12.00, z=270.50], EntityZombie['Zombie'/163319, l='MpServer', x=224.50, y=43.00, z=247.50], EntityCrocodile['Crocodile'/163322, l='MpServer', x=290.98, y=80.00, z=235.10], EntityCreeper['Creeper'/163320, l='MpServer', x=248.50, y=43.00, z=332.02], EntityCrocodile['Crocodile'/163324, l='MpServer', x=280.50, y=114.00, z=263.00], EntityCrocodile['Crocodile'/163338, l='MpServer', x=298.98, y=92.00, z=240.92], EntityCrocodile['Crocodile'/163348, l='MpServer', x=293.98, y=63.00, z=233.00], EntityCrocodile['Crocodile'/163355, l='MpServer', x=292.18, y=76.00, z=240.50], EntityCrocodile['Crocodile'/163353, l='MpServer', x=286.63, y=74.00, z=237.95], EntityCrocodile['Crocodile'/163361, l='MpServer', x=273.74, y=64.00, z=247.14], EntityCrocodile['Crocodile'/163367, l='MpServer', x=296.85, y=63.00, z=235.23], EntityCrocodile['Crocodile'/163390, l='MpServer', x=259.88, y=69.00, z=239.18], EntityCrocodile['Crocodile'/163398, l='MpServer', x=301.50, y=74.53, z=238.99], EntityCrocodile['Crocodile'/163397, l='MpServer', x=293.98, y=76.00, z=240.91], EntityCrocodile['Crocodile'/163413, l='MpServer', x=304.50, y=66.00, z=234.50], EntityCrocodile['Crocodile'/163418, l='MpServer', x=308.50, y=70.00, z=232.50], EntityCrocodile['Crocodile'/163417, l='MpServer', x=300.01, y=76.00, z=239.90], EntityCrocodile['Crocodile'/163422, l='MpServer', x=302.50, y=76.00, z=239.50], EntityCrocodile['Crocodile'/163424, l='MpServer', x=284.50, y=70.00, z=238.50], EntityCrocodile['Crocodile'/163425, l='MpServer', x=292.50, y=66.00, z=234.50], EntityCrocodileSwimming['entity.tfa_crocodile_swimming.name'/163429, l='MpServer', x=277.35, y=62.54, z=241.50], EntityPlayerSP['barttraeger'/2508, l='MpServer', x=278.02, y=68.55, z=300.06], EntityCrocodile['Crocodile'/6015, l='MpServer', x=296.85, y=95.00, z=240.93]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1445714912 bytes (1378 MB) / 5368709120 bytes (5120 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 9 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx6144m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.4.2760 Optifine OptiFine_1.12.2_HD_U_E2 88 mods loaded, 88 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version              | Source                                                       | Signature                                |
	|:--------- |:------------------------ |:-------------------- |:------------------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2               | minecraft.jar                                                | None                                     |
	| UCHIJAAAA | mcp                      | 9.42                 | minecraft.jar                                                | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99            | forge-1.12.2-14.23.4.2760-universal.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.4.2760         | forge-1.12.2-14.23.4.2760-universal.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | foamfixcore              | 7.7.4                | minecraft.jar                                                | None                                     |
	| UCHIJAAAA | clothesline-hooks        | 1.12.2-0.0.1.0       | minecraft.jar                                                | None                                     |
	| UCHIJAAAA | fenceoverhaul            | 1.3.2                | [1.12]FenceOverhaul-1.3.2.jar                                | None                                     |
	| UCHIJAAAA | additionalstructures     | 1.5.0                | Additional Structures 1.12.2 by XxRexRaptorxX  (v.1.5.0).jar | None                                     |
	| UCHIJAAAA | codechickenlib           | 3.2.1.351            | CodeChickenLib-1.12.2-3.2.1.351-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ancientwarfare           | 1.12.2-2.6.1.390     | ancientwarfare-1.12.2-2.6.1.390.jar                          | None                                     |
	| UCHIJAAAA | redstoneflux             | 2.1.0                | RedstoneFlux-1.12-2.1.0.6-universal.jar                      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | ancientwarfareautomation | 1.12.2-2.6.1.390     | ancientwarfare-1.12.2-2.6.1.390.jar                          | None                                     |
	| UCHIJAAAA | ancientwarfarenpc        | 1.12.2-2.6.1.390     | ancientwarfare-1.12.2-2.6.1.390.jar                          | None                                     |
	| UCHIJAAAA | ancientwarfarestructure  | @VERSION@            | ancientwarfare-1.12.2-2.6.1.390.jar                          | None                                     |
	| UCHIJAAAA | ancientwarfarevehicle    | 1.12.2-2.6.1.390     | ancientwarfare-1.12.2-2.6.1.390.jar                          | None                                     |
	| UCHIJAAAA | biomesoplenty            | 7.0.1.2399           | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar                | None                                     |
	| UCHIJAAAA | craftstudioapi           | 1.0.0                | CraftStudio-1.0.0.93-mc1.12-alpha.jar                        | None                                     |
	| UCHIJAAAA | harvestcraft             | 1.12.2z              | Pam's+HarvestCraft+1.12.2z.jar                               | None                                     |
	| UCHIJAAAA | ctm                      | MC1.12.2-0.3.2.18    | CTM-MC1.12.2-0.3.2.18.jar                                    | None                                     |
	| UCHIJAAAA | jei                      | 4.13.0.218           | jei_1.12.2-4.13.0.218.jar                                    | None                                     |
	| UCHIJAAAA | chisel                   | MC1.12.2-0.2.1.35    | Chisel-MC1.12.2-0.2.1.35.jar                                 | None                                     |
	| UCHIJAAAA | mantle                   | 1.12-1.3.2.24        | Mantle-1.12-1.3.2.24.jar                                     | None                                     |
	| UCHIJAAAA | tconstruct               | 1.12.2-2.10.1.87     | TConstruct-1.12.2-2.10.1.87.jar                              | None                                     |
	| UCHIJAAAA | immersiveengineering     | 0.12-85              | ImmersiveEngineering-0.12-85.jar                             | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | geolosys                 | 2.1.2                | Geolosys-1.12.2-2.1.2.jar                                    | None                                     |
	| UCHIJAAAA | traverse                 | 1.6.0                | Traverse-1.12.2-1.6.0-69.jar                                 | None                                     |
	| UCHIJAAAA | pvj                      | 1.4.0                | ProjectVibrantJourneys-1.12.2-1.4.0.jar                      | None                                     |
	| UCHIJAAAA | betterwithmods           | 1.12-2.3.15          | BetterWithMods-1.12-2.3.15.jar                               | None                                     |
	| UCHIJAAAA | quark                    | r1.5-129             | Quark-r1.5-129.jar                                           | None                                     |
	| UCHIJAAAA | animania                 | 1.5.1.1              | animania-1.12.2-1.5.1.1.jar                                  | None                                     |
	| UCHIJAAAA | athenaeum                | 1.12.2-1.14.0        | athenaeum-1.12.2-1.14.0.jar                                  | None                                     |
	| UCHIJAAAA | atomicscience            | 1.12.2-3.1.0.39      | Atomic-Science-1.12.2-3.1.0b39.jar                           | None                                     |
	| UCHIJAAAA | autoreglib               | 1.3-20               | AutoRegLib-1.3-20.jar                                        | None                                     |
	| UCHIJAAAA | base                     | 3.10.0               | base-1.12.2-3.10.0.jar                                       | None                                     |
	| UCHIJAAAA | baubles                  | 1.5.2                | Baubles-1.12-1.5.2 (1).jar                                   | None                                     |
	| UCHIJAAAA | bdlib                    | 1.14.3.12            | bdlib-1.14.3.12-mc1.12.2.jar                                 | None                                     |
	| UCHIJAAAA | betteradvancements       | 0.0.14.66            | BetterAdvancements-1.12.2-0.0.14.66.jar                      | None                                     |
	| UCHIJAAAA | betterfoliage            | 2.1.10               | BetterFoliage-MC1.12-2.1.10.jar                              | None                                     |
	| UCHIJAAAA | betterquesting           | 3.5.270              | BetterQuesting-3.5.270.jar                                   | None                                     |
	| UCHIJAAAA | betterwithengineering    | 1.2                  | BetterWithEngineering-1.6.jar                                | None                                     |
	| UCHIJAAAA | bibliotheca              | 1.3.3-1.12.2         | bibliotheca-1.3.3-1.12.2.jar                                 | None                                     |
	| UCHIJAAAA | bookshelf                | 2.3.565              | Bookshelf-1.12.2-2.3.565.jar                                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | ceramics                 | 1.12-1.3.4           | Ceramics-1.12-1.3.4.jar                                      | None                                     |
	| UCHIJAAAA | chopdownupdated          | 1.1.3                | ChopDown+Updated+(1.12.2+)-1.1.3.jar                         | None                                     |
	| UCHIJAAAA | cookingforblockheads     | 6.4.63               | CookingForBlockheads_1.12.2-6.4.63.jar                       | None                                     |
	| UCHIJAAAA | dsurround                | 3.4.9.16             | DynamicSurroundings-1.12.2-3.4.9.16.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAA | presets                  | 3.4.9.16             | DynamicSurroundings-1.12.2-3.4.9.16.jar                      | None                                     |
	| UCHIJAAAA | easiervillagertrading    | 1.12.2               | easiervillagertrading-2.0.jar                                | None                                     |
	| UCHIJAAAA | enchdesc                 | 1.1.12               | EnchantmentDescriptions-1.12.2-1.1.12.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | zerocore                 | 1.12-0.1.2.2         | zerocore-1.12-0.1.2.2 (1).jar                                | None                                     |
	| UCHIJAAAA | bigreactors              | 1.12.2-0.4.5.49      | ExtremeReactors-1.12.2-0.4.5.49.jar                          | None                                     |
	| UCHIJAAAA | foamfix                  | 0.10.2-1.12.2        | foamfix-0.10.2-1.12.2.jar                                    | None                                     |
	| UCHIJAAAA | forgelin                 | 1.7.4                | Forgelin-1.7.4 (1).jar                                       | None                                     |
	| UCHIJAAAA | ftblib                   | 5.3.0.53             | FTBLib-5.3.0.53.jar                                          | None                                     |
	| UCHIJAAAA | ftbguides                | 1.0.2.22             | FTBGuides-1.0.2.22.jar                                       | None                                     |
	| UCHIJAAAA | ftbutilities             | 5.3.0.51             | FTBUtilities-5.3.0.51.jar                                    | None                                     |
	| UCHIJAAAA | cfm                      | 5.14.0               | furniture-5.14.0-1.12.2.jar                                  | None                                     |
	| UCHIJAAAA | waila                    | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                                  | None                                     |
	| UCHIJAAAA | igwmod                   | 1.4.4-15             | IGW-Mod-1.12.2-1.4.4-15-universal.jar                        | None                                     |
	| UCHIJAAAA | industrialrenewal        | 0.6.0                | IndustrialRenewal_1.12.2-0.6.0.jar                           | None                                     |
	| UCHIJAAAA | itank                    | 1.2.1-1.12.2         | ITank-1.2.1-1.12.2.jar                                       | None                                     |
	| UCHIJAAAA | journeymap               | 1.12.2-5.5.2         | journeymap-1.12.2-5.5.2.jar                                  | None                                     |
	| UCHIJAAAA | jeresources              | 0.8.10.50            | JustEnoughResources-1.12.2-0.8.10.50.jar                     | None                                     |
	| UCHIJAAAA | magneticraft             | 2.5.2                | Magneticraft_1.12-2.5.2-dev.jar                              | None                                     |
	| UCHIJAAAA | mcjtylib_ng              | 3.0.5                | mcjtylib-1.12-3.0.5.jar                                      | None                                     |
	| UCHIJAAAA | minecolonies             | 1.12.2-0.9.149-ALPHA | minecolonies-1.12.2-0.9.149-ALPHA-universal.jar              | None                                     |
	| UCHIJAAAA | modelloader              | 1.1.5                | modelloader-1.1.5.jar                                        | None                                     |
	| UCHIJAAAA | moreoverlays             | 1.14                 | moreoverlays-1.14-mc1.12.2.jar                               | None                                     |
	| UCHIJAAAA | rustic                   | 1.0.10               | rustic-1.0.10.jar                                            | None                                     |
	| UCHIJAAAA | notreepunching           | 1.4.13               | notreepunching-1.4.13.jar                                    | None                                     |
	| UCHIJAAAA | ore_stone_variants       | 4.1                  | ore_stone_variants-4.1.jar                                   | None                                     |
	| UCHIJAAAA | placebo                  | 1.4.1                | Placebo-1.12.2-1.4.1.jar                                     | None                                     |
	| UCHIJAAAA | pneumaticcraft           | 1.12.2-0.8.1-274     | pneumaticcraft-repressurized-1.12.2-0.8.1-274.jar            | None                                     |
	| UCHIJAAAA | rsgauges                 | mc1.12.2-1.0.3b1     | rsgauges-mc1.12.2-1.0.3b1.jar                                | None                                     |
	| UCHIJAAAA | ruins                    | 17.1                 | Ruins-1.12.2.jar                                             | None                                     |
	| UCHIJAAAA | spartanweaponry          | beta 1.2.2           | SpartanWeaponry-1.12.2-beta-1.2.2.jar                        | None                                     |
	| UCHIJAAAA | bq_standard              | 3.4.145              | StandardExpansion-3.4.145.jar                                | None                                     |
	| UCHIJAAAA | subterranaenwaters       | 1.12.2-1.5.6         | subh2o-1.12.2-1.5.6.jar                                      | None                                     |
	| UCHIJAAAA | tesla                    | 1.0.63               | Tesla-1.12.2-1.0.63.jar                                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | teslacorelib             | 1.0.15               | tesla-core-lib-1.12.2-1.0.15.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | tfa                      | 1.1                  | TFA_1.1.jar                                                  | None                                     |
	| UCHIJAAAA | toolbelt                 | 1.7.1                | ToolBelt-1.12.0-1.7.1.jar                                    | None                                     |
	| UCHIJAAAA | unlimitedchiselworks     | 0.2.0                | UnlimitedChiselWorks-0.2.0.jar                               | None                                     |
	| UCHIJAAAA | wawla                    | 2.5.264              | Wawla-1.12.2-2.5.264.jar                                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | clothesline              | 1.12.2-0.0.1.0       | clothesline-1.12.2-0.0.1.0-bundle.jar                        | 3bae2d07b93a5971335cb2de15230c19c103db32 |
	| UCHIJAAAA | dropt                    | 1.12.2-1.10.2        | dropt-1.12.2-1.10.2.jar                                      | None                                     |
	| UCHIJAAAA | teslacorelib_registries  | 1.0.15               | tesla-core-lib-1.12.2-1.0.15.jar                             | None                                     |
	| UCHIJAAAA | wrapup                   | 1.12-1.1.3           | WrapUp-1.12-1.1.3.jar                                        | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ForgelinPlugin (Forgelin-1.7.4 (1).jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  org.blockartistry.DynSurround.asm.Transformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
LoadingPlugin (Quark-r1.5-129.jar)
  vazkii.quark.base.asm.ClassTransformer
clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.0.jar)
  com.jamieswhiteshirt.clothesline.hooks.plugin.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13537 Compatibility Profile Context 24.20.13001.1010' Renderer: 'AMD Radeon HD 7900 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* Base|API (1.0.0) from base-1.12.2-3.10.0.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2 (1).jar
		* betteradvancements|API (0.0.14.66) from BetterAdvancements-1.12.2-0.0.14.66.jar
		* BetterQuesting|API (3.1) from BetterQuesting-3.5.270.jar
		* BetterQuesting|API2 (3.1) from BetterQuesting-3.5.270.jar
		* BetterWithModsAPI (Beta 0.6) from Quark-r1.5-129.jar
		* betterwithmodsAPI (1.12-2.3.15) from BetterWithMods-1.12-2.3.15.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.49.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-85.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-85.jar
		* jeresources|API (0.8.10.50) from JustEnoughResources-1.12.2-0.8.10.50.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.13.0.218.jar
		* MagneticraftAPI (1.0.0) from Magneticraft_1.12-2.5.2-dev.jar
		* Model-Loader (1.1.0) from modelloader-1.1.5.jar
		* PneumaticCraftApi (1.1) from pneumaticcraft-repressurized-1.12.2-0.8.1-274.jar
		* QuarkAPI (2) from Quark-r1.5-129.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* spartanweaponry_api (3) from SpartanWeaponry-1.12.2-beta-1.2.2.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2 (1).jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2 (1).jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2 (1).jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2 (1).jar
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7900 Series GL version 4.5.13537 Compatibility Profile Context 24.20.13001.1010, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Rails+3D.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13537 Compatibility Profile Context 24.20.13001.1010
	OpenGlRenderer: AMD Radeon HD 7900 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by JamiesWhiteShirt** [comment]
I can confirm this is an issue and a fix will be made.
