### ISSUE TITLE
Rope not rendering with iChunUtil mod

### ISSUE THREAD

**Issue by Gabby16bit** [JamiesWhiteShirt/clothesline#16]
Hi, i'm using this mod with the portal gun mod and ichun, and i have discovered that if i put this mod and iChunUtil only (needed for portal gun mod) i can't place the ropes anymore, is there a way to fix this?
Mod version iChun 1.12.2-7.1.4.
 Thank you for the fantastic mod btw.

**Comment by JamiesWhiteShirt** [comment]
Fixed in 1.12.2-0.0.2.2

**Comment by Gabby16bit** [comment]
amazing! Thanks a lot!
